### PR TITLE
Fancy changes.

### PR DESCRIPTION
**Pull request by williamboman**
I know this repo is dead since years, but I just found it - and I have a thing for putting new life to old repos :).

Small fixes/updates such as
- pressing enter actually submits input
- saves video in hash & loads eventual video specified in hash on page load
- bump copyright year
- accept & parse a wider range of input formats

### CODE REVIEW

**Comment by arthurgouveia** [comment]
Hahaha! Nice!

This was just a simple experiment and I wasn't planning on doing anything special with it any longer at all, so your changes are much welcome and appreciated.

Happy 2015 :)

**Comment by williamboman** [comment]
Not sure if I broke anything tbh, didn't really test the old functionality. I'm gonna host this, privately & secretly, on my public server and use it so I'm sure there'll more patches soon.
Happy 2015 to you too!

**Comment by arthurgouveia** [comment]
Seems to be working.

http://arthurgouveia.com/youRepeat/

**Comment by williamboman** [comment]
It doesn't loop for me. According to the docs it'll only loop the initial video.

I'll take a look at it and PR.

**Pull request merged**
